server:
  port: ${SERVER_PORT:9002}

spring:
  application:
    name: praesto
  config:
    import: file:.env.properties
  data:
    mongodb:
      uri: mongodb://${MONGO_USER:admin}:${MONGO_PASSWORD:admin123}@${DB_HOST:localhost}:${DB_PORT:27017}/${DATABASE:general}?authSource=admin
  rabbitmq:
    host: ${RABBITMQ_HOST:localhost}
    port: ${RABBITMQ_PORT:5672}
    username: ${RABBITMQ_USERNAME:admin}
    password: ${RABBITMQ_PASSWORD:admin}

eureka:
  client:
    service-url:
      defaultZone: ${DISCOVERY-URL:http://localhost:8999/eureka/}
    register-with-eureka: true
    fetch-registry: true
  instance:
    metadata-map:
      protocol: websocket
      ws-endpoint: /ws
    prefer-ip-address: true
    instance-id: ${INSTANCE_ID:${spring.application.name}:${server.port}}